### ISSUE TITLE
vite模板 跑起来 less变量无效

### ISSUE THREAD

**Issue by xiaojingyuaner** [3lang3/react-vant-template#1]
![image](https://user-images.githubusercontent.com/24470322/137297167-5ee0bab2-e74d-4b6a-ba01-b66fd676745e.png)
vite模板 跑起来 我加了个组件circle 然后看到样式并没有加载，这个例子，按钮也没有样式。跑起来就是这样

**Comment by 3lang3** [comment]
fix by 3916e066afbe66eade57985af55d0aa386b10083

**Comment by xiaojingyuaner** [comment]
我在修复的基础上又 试了一个组件 Cascader，然后就报错了，因该连带着影响了吧，其他组件我还没一个个实验
![image](https://user-images.githubusercontent.com/24470322/137450421-2f7ae77c-0b1e-4a09-9fc5-b59d2c68c66f.png)
