### ISSUE TITLE
最新的模板跑起来 Cascader 级联选择 有问题

### ISSUE THREAD

**Issue by xiaojingyuaner** [3lang3/react-vant-template#3]
![image](https://user-images.githubusercontent.com/24470322/137513613-43091afe-758d-455d-8487-865ec5238e78.png)
![image](https://user-images.githubusercontent.com/24470322/137513707-a191724a-de72-4f7a-98db-587177eddbb9.png)

![image](https://user-images.githubusercontent.com/24470322/137512851-df1eaa70-b845-4a8d-9065-8275dcb475d0.png)

最新的模板可以跑起来，但是 Cascader 级联选择 还是有问题，样式也错位了

**Comment by xiaojingyuaner** [comment]
是的，
![image](https://user-images.githubusercontent.com/24470322/137570305-d6f40058-cd20-40e9-a0e7-634b030cbf39.png)

**Comment by xiaojingyuaner** [comment]
![image](https://user-images.githubusercontent.com/24470322/137573829-0bd00888-28b8-4723-8846-d701e005b4e8.png)
swiper 组件样式错位，也是报同样的错

**Comment by 3lang3** [comment]
@xiaojingyuaner 更新了最新的vite demo，没发现问题，你拉下demo代码，重新装下依赖再试试？

**Comment by xiaojingyuaner** [comment]
嗯，react-vant 要选择 1.2.0的，就可以了
