### ISSUE TITLE
react-vite 模板中 打包后发现并没有按需引入，大部分没用的组件都引入了

### ISSUE THREAD

**Issue by xiaojingyuaner** [3lang3/react-vant-template#5]
![image](https://user-images.githubusercontent.com/24470322/140254183-fbdc8c2b-09cf-499c-ba3a-7981b8c45b87.png)
实际上我指引用了其中6个组件，其他都未引入，vite是否需要特殊配置 也引入 ts-import-plugin 插件 进行配置？

**Comment by 3lang3** [comment]
应该需要额外配置，你可以先尝试下哈，我有时间跟进下。

**Comment by 3lang3** [comment]
@xiaojingyuaner 找到问题了，不需要vite项目内额外配置，react-vant的package.json需要调整

**Comment by 3lang3** [comment]
https://github.com/3lang3/react-vant/issues/145

**Comment by 3lang3** [comment]
@xiaojingyuaner 还有问题，要调整估计要点时间。
简单说就是，vite打包可以，但是webpack不行。。
组件结构要调整才能两边同时支持，你也可以找下vite有没有什么tree sharking的插件

**Comment by 3lang3** [comment]
@xiaojingyuaner 已修复
